stages:
  data_ingestion:
   cmd:  python ./src/plant_disease_classification/pipeline/data_ingestion_pipeline.py
   deps:
     - config/config.yaml
     - params.yaml
   outs:
    - artifacts/data_ingestion/data

  base_model_preparation:
    cmd:  python ./src/plant_disease_classification/pipeline/data_preparebasemodel_pipeline.py
    deps:
     - artifacts/data_ingestion/data
     - config/config.yaml
     - params.yaml

  training_base_model:
   cmd:  python ./src/plant_disease_classification/pipeline/model_training_pipeline.py
   deps:
    - config/config.yaml
    - params.yaml

    
