artifacts_root: artifacts
data_ingestion:
  root_dir: artifacts/data_ingestion
  source_URL: nirmalsankalana/plant-disease-test-dataset
  local_data_file: artifacts/data_ingestion/plant-disease-test-dataset.zip
  unzip_dir: artifacts/data_ingestion
  